package com.itdfq.dao;

import com.itdfq.domain.DfqUsers;
import com.itdfq.domain.DfqUsersExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DfqUsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dfq_users
     *
     * @mbg.generated
     */
    long countByExample(DfqUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dfq_users
     *
     * @mbg.generated
     */
    int deleteByExample(DfqUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dfq_users
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dfq_users
     *
     * @mbg.generated
     */
    int insert(DfqUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dfq_users
     *
     * @mbg.generated
     */
    int insertSelective(DfqUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dfq_users
     *
     * @mbg.generated
     */
    List<DfqUsers> selectByExample(DfqUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dfq_users
     *
     * @mbg.generated
     */
    DfqUsers selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dfq_users
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DfqUsers record, @Param("example") DfqUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dfq_users
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DfqUsers record, @Param("example") DfqUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dfq_users
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DfqUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dfq_users
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DfqUsers record);
}